### ISSUE TITLE
Clicking outside of the iron-overlay using with-backdrop does not close the overlay

### ISSUE THREAD

**Issue by dafky2000** [PolymerLabs/iron-overlay#8]
**Reproduce:** In the demo, open the "Animated overlay", toggle the backdrop and click anywhere on the backdrop.

**Result:** Nothing.

**Expected result:** Should close the overlay and fire the appropriate events.

**Comment by valdrinkoshi** [comment]
True, the choice was to consider overlays `with-backdrop` as modals, hence they block click interactions, allowing the user to change the behavior through styles, e.g.
```css
iron-overlay-renderer {
  --iron-backdrop-opened: {
    pointer-events: none;
  }
}
```
But I agree this is confusing. Probably the default behavior should be to just render the backdrop, and allow the user to customize it to be modal through styles. WDYT?
